### ISSUE TITLE
Could you publish this crate to crates.io?

### ISSUE THREAD

**Issue by Jedsek** [gmg137/netease-cloud-music-api#1]
If you think that this crate is fully functional, you could publish it so that we can reuse it to save time.

Thanks!
[How to publish a crate?](https://doc.rust-lang.org/cargo/reference/publishing.html)

**Comment by gmg137** [comment]
Due to the instability of NetEase cloud music api, no release to crate plan for now.

**Comment by Jedsek** [comment]
Ok, thanks!
