### ISSUE TITLE
这个项目的开源协议是什么？

### ISSUE THREAD

**Issue by OnePieceJoker** [gmg137/netease-cloud-music-api#11]
我准备自己练手下，准备使用这个项目，不商用，但是可能会给别人下载使用，请问下这个项目准备设置开源协议吗？

准备什么时候发布crate

**Comment by gmg137** [comment]
这个项目理论上是 netease-cloud-music-gtk 的一部分，所以也应遵循 GPL-V3 开源协议。

目前接口变动频繁，在接口稳定前不会发布到crates。

**Comment by OnePieceJoker** [comment]
好的，了解了，感谢回复
