### ISSUE TITLE
关于MusciApi csrf字段的RefCell

### ISSUE THREAD

**Issue by Initsnow** [gmg137/netease-cloud-music-api#13]
想请教一个问题，目前我的想法是将MusicApi这个结构体设置为全局静态变量来在不同线程但是在同一个Client中进行http请求，但csrf字段为RefCell，所以无法设置，有什么其他办法吗？或是能修改为Mutex、RwLock吗？

**Comment by gmg137** [comment]
我以前在netease-cloud-music-gtk中做过这方面尝试，使用Lazy做的全局共享，可以运行但连接状态没能保存 ，忘了什么原因反正是没弄成，最后改用CookieJar来保存连接状态。

**Comment by Initsnow** [comment]
> 我以前在netease-cloud-music-gtk中做过这方面尝试，使用Lazy做的全局共享，可以运行但连接状态没能保存 ，忘了什么原因反正是没弄成，最后改用CookieJar来保存连接状态。

是库的问题吗？我感觉reqwest比这isahc好一些
