### ISSUE TITLE
是否可以添加Cargo.lock

### ISSUE THREAD

**Issue by OnePieceJoker** [gmg137/netease-cloud-music-api#7]
由于缺少Cargo.lock，在安装netease-cloud-music-gtk4时，该依赖会被锁定到最新的commit，导致编译存在失败的可能性

**Comment by gmg137** [comment]
我已将代码回退到 1.1.1 版本，后续开发将在 dev 分支进行，以防发生类似情况。

**Comment by OnePieceJoker** [comment]
多谢，麻烦了
